### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by sheremet-va** [ai/nanospy#5]
We were hoping to use this library as default mocking lib for `vitest`, but it lacks some features, since we wanted to make jest compatible wrapper. Is it possible to add this features without making the lib much larger?

- getter/setter support
- distinguishing between return/throw (rn throw just stores as `undefined` or wont even be added if `cb` throws)
- an api to replace mock with another one (questionable, since we can do this inside our own wrapper)

**Comment by TrySound** [comment]
Could you provide some examples how it may look?

**Comment by sheremet-va** [comment]
Sure

Getter/setter (showing only getter, but setter follows the same logic)

```ts
let apples = 0

const obj = {
   get apples() {
       return apples
   },
   set apples(a) {
       apples = a
   }
}

const spy = spyOn(obj, 'apples', 'get', () => 55)
// or
const spy = spyOn(obj, { getter: 'apples' }, () => 55)

console.log(obj.apples) // 55
```
Healthy returns
```ts
let count = 0
const obj = {
   follow() {
      if(count === 1) {
         throw new Error()
      }
      return ++count
  }
}
const spy = spyOn(obj, 'follow')

obj.follow()
try {
   obj.follow()
} catch () {}


spy.returns // [1, Error] or [{ type: 'return', value: 1}, { type: 'throw', value: Error }] (since you can throw anything) - or any other suitable way
```

Remocking
```ts
const spy = spyOn(obj, 'follow')

spy.willCall(() => console.log('baz'))

obj.follow() // console.log('baz')
```

**Comment by ai** [comment]
It seems like it is a 3 separated feature requests.

1. `spyOn(obj, { getter: 'apples' }, () => 55)` is better. How it will complicate the code?
2. Mixins errors and returns looks like a dangerous thing for me. All ways look unpredictable. But maybe we can split `returns` and `results`?
3. I like the idea of remocking. Please send PR.
